project:
  type: website
  output-dir: site

website:
  title: ""
  navbar:
    background: "#006E9C"
    logo: posts/_images/CRCLOGO.png
    right:
    - text: "CRC Homepage"
      href: http://www.ctriver.org
    - text: "Is It Clean?"
      href: http://www.connecticutriver.us	

execution:
  freeze: auto


format:
  html:
    mainfont: Open Sans
    linkcolor: "#5ECCF3"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]