---
title: "DRAFT 2024 Basin 12 Water Quality Review"
author: "Ryan O'Donnell"
desription: "Three year summary of water quality results collected by Deerfield River Watershed Association volunteers"
date: "11/20/2024"
format:
  html:
    df-print: paged
    toc: true
    echo: false
    warning: false
categories:
  - Deerfield River
  - North River
  - Green River
  - Beaver Brook
  - Whetstone Brook
  - Broad Brook
  - Chloride
  - Nitrogen
  - Phosphorus
  - Bacteria
  - E. coli
  - Turbidity
  - Conductivity
  - Tributaries
  - Basin 12
  - Vermont
---

```{r library}

library(tidyverse)
library(readxl)
library(lubridate)
library(maps)
library(mapproj)
library(sf)
library(patchwork)
library(ggiraph)
library(maps)
library(mapproj)
library(ggtext)
library(scales)
library(htmlwidgets)
library(gt)
library(EnvStats)

```

```{r data}

### 1/3/25 note - 2022 Conductivity data is MISSING from Whetstone brook

Basin12 <- read_xlsx("_data/24Basin12Data.xlsx") %>%
  separate(`SiteID`, c("State", "River", "Mile"), sep = "-|_", remove = FALSE) %>%
  drop_na(ResultValue) %>%
  mutate(
    Mile = as.numeric(Mile),
    ResultCalc = case_when(
      str_detect(ResultValue, "<") ~ parse_number(ResultValue)/2,
      str_detect(ResultValue, ">") ~ parse_number(ResultValue),
      TRUE ~ as.numeric(ResultValue)
    ),
    Group = case_when(
      River == "BRD" ~ "CT River Tributaries",
      River == "BVR" ~ "Deerfield Tributaries",
      River == "EBN" ~ "North River",
      River == "NBD" ~ "North Branch Deerfield River",
      River == "NWT" ~ "CT River Tributaries",
      River == "ELS" ~ "Deerfield Tributaries",
      River == "WET" ~ "Whetstone Brook",
      River == "GRN" ~ "Green River",
      River == "COB" ~ "Deerfield Tributaries",
      River == "PND" ~ "Green Tributaries",
      River == "HBG" ~ "Green Tributaries",
      River == "NEG" ~ "Deerfield Tributaries"
    ),
    WeatherStatus = case_when(
      WeatherStatus == "Y" ~ "Wet",
      WeatherStatus == "N" ~ "Dry",
      TRUE ~ WeatherStatus
    ),
    "SampleYear" = as.character(year(SampleDate)),
      SiteID = case_when(
      SiteID == "VT-ELS_00.2" & SampleYear < 2023 ~ "VT-NEG_00.2",
      TRUE ~ SiteID
    ),
    FlowCondition = factor(FlowCondition, levels = c("Low", "Moderate", "High"))) %>%
  rename(ChartName = `Chart Name`)

wetdry_colors <- c("Dry" = "#44AA99", "Wet" = "#554499")
lmh_colors <- c("Low" = "#88CCEE", "Moderate" = "#DDCC77", "High" = "#CC6677")
standardcolor <- "#AA4499"
standardcolor2 <- "#442222"
yearcolors <- c("2014" = "#202547FF",
                "2015" = "#43444AFF",
                "2016" = "#5F654AFF",
                "2017" = "#7B8948FF",
                "2018" = "#97B043FF",
                "2019" = "#B2D736FF",
                "2020" = "#CEFF1AFF",
                "2021" = "#D8E01BFF",
                "2022" = "#DFC11BFF",
                "2023" = "#E2A11BFF")

watersheds <- unique(Basin12$Group)

# add a dummy row for every site and year combo to make sure every site shows up on every graph

# generate the possible combinations for each watershed group

Basin12_expanded <- Basin12 %>%
  group_by(Group) %>%
  expand(SiteID, Parameter, FlowCondition, WeatherStatus, SampleYear)

# join to data and fill in important repeated information

Basin12NAs <- Basin12 %>%
  bind_rows(., Basin12_expanded) %>%
  group_by(SiteID) %>%
  fill(c(State:ChartName)) %>%
  ungroup() %>%
  group_by(Parameter) %>%
  fill(ResultUnit) %>%
  ungroup() %>%
  mutate(ResultCalc = as.numeric(ResultCalc),
         FlowCondition = factor(FlowCondition, levels = c("Low", "Moderate", "High")))

```

INTRO

# Basin 12 Overview

## Volunteer Water Quality Monitoring History

### Monitoring Locations

### Parameters

# Monitoring Results

## Bacteria
```{r bacteria set-up}

bacteria_data <- Basin12 %>%
  filter(Parameter == "E. coli") %>%
  filter(SiteID != "VT-NWT_01.0") %>%
  filter(SiteID != "VT-NBD_12.5") %>%
  filter(SiteID != "VT-NBD_01.3")

ECmax <- max(bacteria_data$ResultCalc, na.rm = TRUE)

swim_limit = 235

```

::: {.panel-tabset group="watershed"}

```{r bacteria graphs}
#| output: asis
#| echo: false

res <- purrr::map_chr(watersheds, \(.watershed) {
    knitr::knit_child(
      input = "_childcodes/_B12_EC.qmd", 
      envir = environment(), 
      quiet = TRUE
      )
  })

cat(res, sep = '\n\n')
```

:::

## Nutrients
```{r nutrients set-up}

nutrient_data <- Basin12 %>%
  filter(Parameter %in% c("Total Nitrogen", "Total Phosphorus")) %>%
  filter(SiteID != "VT-NBD_01.3") %>%
  arrange(FlowCondition)

TNmax <- nutrient_data %>%
  filter(Parameter == "Total Nitrogen")

TNmax <- max(TNmax$ResultCalc, na.rm = TRUE)

TN_standard <- 0.38

TPmax <- nutrient_data %>%
  filter(Parameter == "Total Phosphorus")

TPmax <- max(TPmax$ResultCalc, na.rm = TRUE)

TP_standardA1 <- 9
TP_standardB2 <- 15

```

::: {.panel-tabset group="watershed"}

```{r nutrient graphs}
#| output: asis
#| echo: false

res <- purrr::map_chr(watersheds, \(.watershed) {
    knitr::knit_child(
      input = "_childcodes/_B12_nutrient.qmd", 
      envir = environment(), 
      quiet = TRUE
      )
  })

cat(res, sep = '\n\n')
```

:::

## Chloride/Conductivity

```{r cl cond set-up}

clcond_data <- Basin12NAs %>%
  filter(Parameter %in% c("Total Chloride", "Specific Conductance")) %>%
  filter(SiteID != "VT-NBD_01.3") %>%
  arrange(FlowCondition)

condmax <- clcond_data %>%
  filter(Parameter == "Specific Conductance")

condmax <- max(condmax$ResultCalc, na.rm = TRUE)

CLmax <- clcond_data %>%
  filter(Parameter == "Total Chloride")

CLmax <- max(CLmax$ResultCalc, na.rm = TRUE)

```

::: {.panel-tabset group="watershed"}

```{r cl cond graphs}
#| output: asis
#| echo: false

res <- purrr::map_chr(watersheds, \(.watershed) {
    knitr::knit_child(
      input = "_childcodes/_B12_cl_cond.qmd", 
      envir = environment(), 
      quiet = TRUE
      )
  })

cat(res, sep = '\n\n')
```

:::

## Turbidity

```{r turb set-up}

turb_data <- Basin12NAs %>%
  filter(Parameter %in% c("Turbidity")) %>%
  filter(SiteID != "VT-NBD_01.3") %>%
  arrange(FlowCondition)

turbmax <- max(turb_data$ResultCalc, na.rm = TRUE)

turb_standard_A1 <- 10
turb_standard_other <- 25

```

::: {.panel-tabset group="watershed"}

```{r turb graphs}
#| output: asis
#| echo: false

res <- purrr::map_chr(watersheds, \(.watershed) {
    knitr::knit_child(
      input = "_childcodes/_B12_turb.qmd", 
      envir = environment(), 
      quiet = TRUE
      )
  })

cat(res, sep = '\n\n')
```

:::

## Discussion

## 


# Next Steps

# Complete Results